/// @description UpdateSeed(seedsMapIndex)
/// @param seedsMapIndex

var seedMap = oGameManager.seeds[argument0];

// The seed's stats.
name      = seedMap[? "Name"];       // Comment this later...
price     = seedMap[? "Price"];      // Comment this later...
growRate  = seedMap[? "Grow Rate"];  // Comment this later...
coinValue = seedMap[? "Coin Value"]; // Comment this later...
